[package]
name = "constellation"
version = "0.1.0"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]

[dependencies]
fnv = "1.0.3"
mopa = "0.2"
crossbeam = "0.2"
rayon = "0.5.0"
arrayvec = "0.3.20"
tuple_utils = "0.2"
atom = "0.3"
